#!/bin/sh
if [ -z "$WORKSPACE" ]; then echo "environment WORKSPACE is not set";exit 1;fi
if [ $# -eq 0 ]; then echo -e "usage:\n   $(basename "$0") <project>\nwhere project is a github repository in $WORKSPACE";exit 2;fi

cd $WORKSPACE/$1 &&
git remote set-url origin git@github.com:calint/$1.git &&
git add . &&
git commit -m "."
git push --all &&
TS=$(date +%Y-%m-%d--%H-%M) &&
echo $TS &&
git tag $TS &&
git push --tags
