# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("accessibility.typeaheadfind", true);
user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1300595174);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1300595294);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1300508774);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1300649938);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 314915);
user_pref("browser.download.dir", "~/downloads");
user_pref("browser.download.folderList", 2);
user_pref("browser.download.save_converter_index", 0);
user_pref("browser.migration.version", 5);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage", "http://localhost:8888/");
user_pref("browser.startup.homepage_override.buildID", "2011022200");
user_pref("browser.startup.homepage_override.mstone", "rv:2.0b12");
user_pref("browser.startup.page", 0);
user_pref("browser.tabs.autoHide", true);
user_pref("distribution.openSUSE.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCount", 2);
user_pref("extensions.blocklist.totalPingCount", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 3);
user_pref("extensions.dictionary.com.firstRun", false);
user_pref("extensions.enabledAddons", "{972ce4c6-7e08-4474-a285-3208198ce6fd}:4.0b12");
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"susefox@opensuse.org\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/susefox@opensuse.org\",\"mtime\":1300439625000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1300439624000}}}]");
user_pref("extensions.lastAppVersion", "4.0b12");
user_pref("extensions.pendingOperations", false);
user_pref("idle.lastDailyNotification", 1300592724);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-15, ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1300592724);
user_pref("places.history.expiration.transient_current_max_pages", 41393);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("services.sync.lastversion", "1.7b1pre");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1300592724);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1303250676);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
