#!/bin/sh
WS=/Users/calin/Documents/workspace-2
IP=162.243.127.160
VERBOSE=--verbose
#VERBOSE=   # silent
CMD_RESET='killall java;. /etc/rc.local'
SSH_OPTS='-oBatchMode=yes -oStrictHostKeyChecking=no -oConnectTimeout=60'

DTF=%F---%H:%M:%S-
COLR=

echo "`date +$DTF`  ${COLR}•  update $IP:/a/ from $WS/a/"
for((;;));do
	rsync --recursive $VERVOSE --exclude .svn --exclude u/ $WS/a/  root@$IP:/a/
	if [ $? -eq 0 ];then break;fi
	sleep 1
	echo "`date +$DTF`  ${COLR}·  waiting for update $IP:/a/ from $WS/a/"
done

echo "`date +$DTF`  ${COLR}•  reset $IP with '$CMD_RESET'"
#echo $SSH_OPTS
ssh $SSH_OPTS root@$IP $CMD_RESET

echo "`date +$DTF`  ${COLR}•  wait for http://$IP"
#while [ $(curl $IP) -neq 0 ]; do echo "`date +$DTF`  ${COLR}·  waiting for http://$IP";sleep 1;done;
curl $IP

echo "`date +$DTF`  ${COLR}•  pid"
ssh $SSH_OPTS root@$IP 'ps aux|grep java|sed /grep/d|tr -s " "|cut -d " " -f2'

echo "`date +$DTF`  ${COLR}•  done"
