#!/bin/sh
echo $0

IP=$(if [ -z $1 ];then echo 162.243.127.160;else echo $1;fi)
WS=/Users/calin/Documents/workspace-2
SRC=$WS/a/cloud/digitalocean/ubuntu14.04/

date
echo patch
echo " src: $SRC"
echo "dest: $IP"
echo
rsync --recursive --verbose --progress --exclude .svn -aze 'ssh -oStrictHostKeyChecking=no -oBatchMode=yes' $SRC root@$IP:/
date
ssh root@$IP 'chmod ugo+x /install && /install'
date
ssh root@$IP 'chmod ugo+x /etc/rc.local && /etc/rc.local'
date
ssh root@$IP 'apt-get install gcc clang crafty figlet cowsay fortune'
date
