#!/bin/sh
IP=162.243.127.160
SRC=/Users/calin/Documents/workspace-2/a/cloud/digitalocean/ubuntu14.04/

date
echo patch
echo " src: $SRC"
echo "dest: $IP"
echo
rsync --recursive --verbose --progress --exclude .svn -aze "ssh -oStrictHostKeyChecking=no -oBatchMode=yes" $SRC root@$IP:/
date
ssh root@$IP /install
date
ssh root@$IP '/etc/rc.local&'
date
ssh root@$IP 'apt-get install gcc clang figlet cowsay fortune'
date
