#!/bin/sh
H=localhost:8888                # host
I=140706-124220.172-ba8e10b6    # session id
U=any                           # uri without leading /
N=$'\r'                         # form item delimiter
A='$=-ls'$N                     # ajax field
P=$A-ls-q=$1$N                  # ajax post, method x_ls in a.any with state change _ls_q=$1
V= #--verbose

curl $V --cookie i=$I --header "Content-Type:text/plain" --data-binary "$P" "$H/$U"
